# Generated by Django 5.2.2 on 2025-06-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_type',
            field=models.CharField(choices=[('STOCK', 'Fundo de Ações'), ('BOND', 'Fundo de Renda Fixa'), ('MULTI', 'Fundo Multimercado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Aporte'), ('WITHDRAWAL', 'Resgate')], max_length=10),
        ),
    ]
